In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
dir_datasets = '/content/drive/MyDrive/DataScience/Data Science Course/0.Datasets/{}'
df_population_raw = pd.read_csv(dir_datasets.format('population_total.csv'), encoding='latin-1')

In [4]:
df_population_raw.head()

  country    year    population
0   China  2020.0  1.439324e+09
1   China  2019.0  1.433784e+09
2   China  2018.0  1.427648e+09
3   China  2017.0  1.421022e+09
4   China  2016.0  1.414049e+09

# **MAKING A PIVOT TABLE**

In [5]:
# remove nulls values 
df_population_raw.dropna(inplace = True)

In [8]:
df_population_raw.dtypes

country        object
year            int64
population    float64
dtype: object

In [7]:
df_population_raw['year'] = df_population_raw['year'].astype('int64')

In [11]:
# create a pivot table
df_pivot = df_population_raw.pivot(index='year', 
                              columns='country', 
                              values='population')

In [14]:
# select some countries
df_pivot = df_pivot[['United States', 'India', 'China', 'Indonesia', 'Brazil']]
df_pivot

country  United States         India         China    Indonesia       Brazil
year
1955       171685336.0  4.098806e+08  6.122416e+08   77273425.0   62533919.0
1960       186720571.0  4.505477e+08  6.604081e+08   87751068.0   72179226.0
1965       199733676.0  4.991233e+08  7.242190e+08  100267062.0   83373530.0
1970       209513341.0  5.551898e+08  8.276014e+08  114793178.0   95113265.0
1975       219081251.0  6.231029e+08  9.262409e+08  130680727.0  107216205.0
1980       229476354.0  6.989528e+08  1.000089e+09  147447836.0  120694009.0
1985       240499825.0  7.843600e+08  1.075589e+09  164982451.0  135274080.0
1990       252120309.0  8.732778e+08  1.176884e+09  181413402.0  149003223.0
1995       265163745.0  9.639226e+08  1.240921e+09  196934260.0  162019896.0
2000       281710909.0  1.056576e+09  1.290551e+09  211513823.0  174790340.0
2005       294993511.0  1.147610e+09  1.330776e+09  226289470.0  186127103.0
2010       309011475.0  1.234281e+09  1.368811e+09  241834215.0  195713635.0
2015       320878310.0  1.310152e+09  1.406848e+09  258383256.0  204471769.0
2016       323015995.0  1.324517e+09  1.414049e+09  261556381.0  206163053.0
2017       325084756.0  1.338677e+09  1.421022e+09  264650963.0  207833823.0
2018       327096265.0  1.352642e+09  1.427648e+09  267670543.0  209469323.0
2019       329064917.0  1.366418e+09  1.433784e+09  270625568.0  211049527.0
2020       331002651.0  1.380004e+09  1.439324e+09  273523615.0  212559417.0