In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
dir_datasets = '/content/drive/MyDrive/DataScience/Data Science Course/0.Datasets/{}'
df_laptops = pd.read_csv(dir_datasets.format('laptop_price.csv'), encoding='latin-1')

In [4]:
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

**EXERCISE #1**

In [16]:
# find duplicates en a column 

df_laptops.duplicated('laptop_ID').value_counts()

df_laptops.duplicated('laptop_ID').sum()

0

In [23]:
# show duplicates element of a dataframe 
df_laptops[df_laptops.duplicated('laptop_ID')]

Empty DataFrame
Columns: [laptop_ID, Company, Product, TypeName, Inches, ScreenResolution, Cpu, Ram, Memory, Gpu, OpSys, Weight, Price_euros]
Index: []

In [22]:
# duplicates in 2 o more columns
duplicated = df_laptops.duplicated(['Product', 'TypeName', 'Inches'])

In [26]:
# show all of duplicates values 
df_laptops[duplicated].sort_values(['Product', 'TypeName'])

<ipython-input-26-89b8e28e601e>:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_laptops[duplicated].sort_values(['Product', 'TypeName'])

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1287,1305,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1098,1113,HP,250 G5,Notebook,15.6,1366x768,Intel Pentium Quad Core N3710 1.6GHz,4GB,1TB HDD,Intel HD Graphics 405,Windows 10,1.96kg,500.0
1170,1188,HP,250 G5,Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 520,Windows 10,1.96kg,679.0
10,11,HP,250 G6,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,500GB HDD,Intel HD Graphics 620,No OS,1.86kg,393.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
414,421,Asus,ZenBook Flip,2 in 1 Convertible,13.3,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.27kg,928.0
826,835,Asus,ZenBook Flip,2 in 1 Convertible,13.3,Touchscreen / Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1358.0
1275,1293,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0
1289,1307,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,IPS Panel Full HD 1920x1080,Intel Core M 6Y30 0.9GHz,8GB,512GB SSD,Intel HD Graphics 515,Windows 10,1.2kg,729.0
676,684,Asus,Zenbook 3,Ultrabook,14.0,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,Windows 10,1.1kg,1135.0

**EXERCISE #2**

In [29]:
# order a dataframe asc by "Company" and 'Price'
# cheaper first and more expensive last
df_laptops = df_laptops.sort_values(['Company','Price_euros'], ascending=True)
df_laptops.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1198,1216,Acer,Aspire 3,Notebook,15.6,1366x768,Intel Celeron Dual Core N3350 2GHz,4GB,1TB HDD,Intel HD Graphics 500,Linux,2.1kg,272.0
1277,1295,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg,289.0
1291,1309,Acer,Aspire ES1-531,Notebook,15.6,1366x768,Intel Celeron Dual Core N3060 1.6GHz,4GB,500GB HDD,Intel HD Graphics 400,Linux,2.4kg,289.0
769,778,Acer,Aspire A315-31,Notebook,15.6,1366x768,Intel Pentium Quad Core N4200 1.1GHz,4GB,1TB HDD,Intel HD Graphics 505,Linux,2.1kg,298.0
745,753,Acer,Chromebook 14,Notebook,14.0,1366x768,Intel Celeron Dual Core N3060 1.6GHz,2GB,32GB Flash Storage,Intel HD Graphics 400,Chrome OS,1.68kg,330.0

In [32]:
# check all categories in the column 'Company'
df_laptops.value_counts('Company')

Company
Dell         224
Lenovo       143
HP           136
Acer          44
Asus          24
Apple         15
Toshiba       10
MSI            7
Microsoft      5
Razer          4
Samsung        3
Google         2
Xiaomi         2
Huawei         1
dtype: int64

In [34]:
# duplicate values in the column 'Company' default keep='first'
duplicated_first = df_laptops.duplicated('Company', keep='first')

In [41]:
# show the dataframe with duplicated values in the column 'Company'

df_laptops[duplicated_first] # here we can see all duplicates


# keep='first' 
# show the dataframe with duplicated values in the column 'Company'
df_laptops[~duplicated_first] # the symbol ~ is the same of !, opposite of a value
df_laptops[~duplicated_first][['Company','Price_euros']]
# check all categories
#df_laptops[~duplicated_first].value_counts('Company')

        Company  Price_euros
1198       Acer       272.00
34        Apple       998.00
713        Asus       298.00
377        Dell       309.00
472      Google      1275.00
1282         HP       209.00
214      Huawei      1499.00
1272     Lenovo       229.00
919         MSI      1119.91
457   Microsoft       989.00
1117      Razer      1029.00
812     Samsung      1499.00
159     Toshiba       447.00
877      Xiaomi       935.00

In [43]:
# keep='last'
duplicated_last = df_laptops.duplicated('Company', keep='last') # we get more expensive laptops

In [46]:
# more expensive laptops by Company
df_laptops[~duplicated_last][['Company','Price_euros']]

        Company  Price_euros
1189       Acer      2599.00
17        Apple      2858.00
372        Asus      2199.00
723        Dell      3659.40
762      Google      1559.00
1136         HP      3949.40
214      Huawei      1499.00
610      Lenovo      4899.00
811         MSI      2415.00
449   Microsoft      2589.00
830       Razer      5499.00
892     Samsung      1699.00
307     Toshiba      1043.00
514      Xiaomi      1399.95

In [47]:
# keep=False, meaning that every duplicate values doesnt appear
#show the dataframe without duplicates in the column Company
duplicated_false = df_laptops.duplicated('Company', keep=False)

In [50]:
df_laptops[~duplicated_false][['Company','Price_euros']]

    Company  Price_euros
214  Huawei       1499.0

In [51]:
df_laptops.value_counts('Company')

Company
Dell         224
Lenovo       143
HP           136
Acer          44
Asus          24
Apple         15
Toshiba       10
MSI            7
Microsoft      5
Razer          4
Samsung        3
Google         2
Xiaomi         2
Huawei         1
dtype: int64