In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import pandas as pd
import numpy as np

In [4]:
dir_datasets = '/content/drive/MyDrive/DataScience/Data Science Course/0.Datasets/{}'
df_players = pd.read_csv(dir_datasets.format('players_20.csv'), sep=',')

In [5]:
df_players = df_players[['short_name', 'long_name',	'age',	'dob',	'height_cm',	'weight_kg',	'nationality',	'club']]

In [6]:
df_players.set_index('short_name', inplace=True)

In [7]:
df_players.head()

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid

# **LAMBDA FUNCTION**

In [10]:
# basic function
def sum_values(a, b):
  return  a + b
  
sum_values(2, 3)

5

In [11]:
# lambda function
sum_values_lambda = lambda a,b:a+b

sum_values_lambda(2,3)

5

# **APPLY + LAMBDA FUNCTION**

In [12]:
# use lambda for convert height_cm to meters
df_players['height_cm'].apply(lambda x: x/100)

# alternative
df_players['height_cm']/100

short_name
L. Messi             1.70
Cristiano Ronaldo    1.87
Neymar Jr            1.75
J. Oblak             1.88
E. Hazard            1.75
                     ...
Shao Shuai           1.86
Xiao Mingjie         1.77
Zhang Wei            1.86
Wang Haijian         1.85
Pan Ximing           1.82
Name: height_cm, Length: 18278, dtype: float64

In [19]:
# use the lambda function for convert long_name to uppercase
df_players['long_name'].apply(lambda x: x.upper())

# alternative
df_players['long_name'].str.upper()

short_name
L. Messi                  LIONEL ANDRÉS MESSI CUCCITTINI
Cristiano Ronaldo    CRISTIANO RONALDO DOS SANTOS AVEIRO
Neymar Jr                  NEYMAR DA SILVA SANTOS JUNIOR
J. Oblak                                       JAN OBLAK
E. Hazard                                    EDEN HAZARD
                                    ...
Shao Shuai                                            邵帅
Xiao Mingjie                                MINGJIE XIAO
Zhang Wei                                             张威
Wang Haijian                                         汪海健
Pan Ximing                                           潘喜明
Name: long_name, Length: 18278, dtype: object

In [33]:
# use the lamda function to get the year of "dob"
df_players['dob'] = df_players['dob'].astype('datetime64')

df_players['dob'].apply(lambda x: x.year)

# alternative
df_players['dob'].dt.year

short_name
L. Messi             1987
Cristiano Ronaldo    1985
Neymar Jr            1992
J. Oblak             1993
E. Hazard            1991
                     ...
Shao Shuai           1997
Xiao Mingjie         1997
Zhang Wei            2000
Wang Haijian         2000
Pan Ximing           1993
Name: dob, Length: 18278, dtype: int64

In [40]:
# use the lambda function for the dataframe to get IMC
df_players.apply(lambda x: round(x['weight_kg'] / ((x['height_cm']/100)**2),2), axis=1)

short_name
L. Messi             24.91
Cristiano Ronaldo    23.74
Neymar Jr            22.20
J. Oblak             24.62
E. Hazard            24.16
                     ...
Shao Shuai           22.84
Xiao Mingjie         21.07
Zhang Wei            21.68
Wang Haijian         21.62
Pan Ximing           23.55
Length: 18278, dtype: float64